apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-page
spec:
  replicas: 3
  selector:
    matchLabels:
      app: color-page
  template:
    metadata:
      labels:
        app: color-page
    spec:
      containers:
      - name: color-page
        image: abricioveronez/web-color:blue
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: color-page
spec:
  selector:
    app: color-page
  ports:
  - port: 80  
    targetPort: 80
  type: ClusterIP
